# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_ghmb <- function(y_S, X_S, X_Sa, Z_Sa, Z_U, Omega_S, Sigma_Sa) {
    .Call(`_HMB_cpp_ghmb`, y_S, X_S, X_Sa, Z_Sa, Z_U, Omega_S, Sigma_Sa)
}

cpp_hmb <- function(Y_S, X_S, X_Sa, Z_Sa, Z_U) {
    .Call(`_HMB_cpp_hmb`, Y_S, X_S, X_Sa, Z_Sa, Z_U)
}

